"""gen_engine_registry.py — write config/engine_coefficients.yml from the last
compare_engines.py run (review/engine_comparison.json).

The registry is the auditable record of the three deterrence engines and their
calibrated coefficients per purpose, so a reviewer can reproduce or verify each one
WITHOUT re-running the fit. The SPEC (forms, Grid2Demand published C0 defaults, fit
objective, gates) is framework and committable; the fitted values are regenerable
from local survey data — mark accordingly and keep results local if needed.

Run: python gen_engine_registry.py   (after compare_engines.py)
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
J = os.path.join(HERE, "review", "engine_comparison.json")
OUT = os.path.join(HERE, "config", "engine_coefficients.yml")


def main():
    rows = json.load(open(J))
    L = []
    L += [
        "# Engine coefficient registry — three deterrence engines on the same TRMG2 data.",
        "# Generated by gen_engine_registry.py from review/engine_comparison.json.",
        "# SPEC (forms / C0 defaults / fit objective / gates) is framework. Fitted per-purpose",
        "# values are REGENERABLE from the local survey control totals (keep local if required).",
        "",
        "meta:",
        "  units: {time: congested_minutes, skim: AM_dijkstra}",
        "  magnitude_first: true          # every fit respects the survey mean before shape",
        "  reference_distribution: engine_A_nested_logit   # C's shape target (check-and-balance)",
        "",
        "engines:",
        "  A_nested_logit:",
        "    role: TRMG2-faithful behavioral reference",
        "    form: 'U = size*ln(1+A) + beta_time*(det)*t + iz*I ; nested_dc'",
        "    tuned_parameter: det   # deterrence multiplier on beta_time, calibrated to survey mean",
        "  B_unc_power:",
        "    role: UNC teaching gravity (MyFirstFourStepModel)",
        "    form: 'f = t^(-beta) * A ; row-normalized'",
        "    tuned_parameter: beta  # single power exponent, calibrated to survey mean",
        "  C_grid2demand_gamma:",
        "    role: flexible 2-parameter gamma — tuned to compare & verify",
        "    form: 'f = t^b * exp(c*t) * A ; row-normalized   (grid2demand_0712a_lite.py:1427)'",
        "    tuned_parameters: [b, c]   # b=short-trip peak, c=long tail; BOTH fitted",
        "    trajectory: C0_published_default -> C1_fitted",
        "    fit_objective: '6*((mean-target)/target)^2 + L1(TLFD_C - TLFD_A)'  # mean first, then shape",
        "    optimizer: scipy Nelder-Mead",
        "    published_defaults_source: Grid2Demand NCHRP-716 (grid2demand_0712a_lite.py:1326-1370)",
        "",
        "# ── per-purpose calibrated coefficients ──────────────────────────────────────",
        "purposes:",
    ]
    for r in rows:
        p = r["purpose"]
        L += [
            f"  {p}:",
            f"    survey_mean_min: {r['surv']}",
            f"    target_min: {r['target']}          # survey mean x network-time/survey-len factor",
            f"    A_nested:  {{det: {r['coef_A_det']}, mean: {r['A_atl']}, bias_pct: {r['A_bias']}}}",
            f"    B_power:   {{beta: {r['coef_B_power']}, mean: {r['B_atl']}, bias_pct: {r['B_bias']}}}",
            f"    C_gamma:",
            f"      C0_default: {{b: {r['C0_b']}, c: {r['C0_c']}, mean: {r['C0_atl']}, shape_to_A: {r['C0_shape']}}}",
            f"      C1_fitted:  {{b: {r['C1_b']}, c: {r['C1_c']}, mean: {r['C_atl']}, bias_pct: {r['C_bias']}, shape_to_A: {r['C1_shape']}}}",
        ]
    open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print(f"wrote {os.path.relpath(OUT, HERE)}  ({len(rows)} purposes)")


if __name__ == "__main__":
    main()
